export default [
  {
    isFeedJob: true,
    id: "76260930-0279-4d37-8e93-818c2fabf5c4",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1743963396479,
    parent_grid: 2,
    parent_id: "41e81c5b-2095-4602-abec-9b478ef62447",
    width: 1024,
    height: 1024,
    username_v2: "wntt",
    display_name: "wntt",
    user_id: "7d266123-b26f-4461-98c0-6709b8243511",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 1,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "black and white seamless pattern, reptile scale texture, dense overlapping oval scales, symmetrical organic flow, high contrast, alpha texture style, no borders or dividers, clean lines, vector look, stylized snake skin pattern",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "6a1f1e6b-1122-416c-ba7d-a22d543686fe",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1745864008778,
    parent_grid: 0,
    parent_id: "3de4d9a1-f4f5-4c40-b854-fe586a7c427a",
    width: 1024,
    height: 1024,
    username_v2: "fast.k",
    display_name: "fast.k",
    user_id: "38a1d507-ed39-4574-ba9a-0c0f83d47544",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "2d texture image of a photorealistic 18th century classic wall",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "43b43baf-61a6-44f7-ae6f-43a3affe4f3d",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1748338525024,
    parent_grid: 2,
    parent_id: "7ee7414f-4415-404f-a2ba-f9208c0e2158",
    width: 1024,
    height: 1024,
    username_v2: "u9386782323",
    display_name: "u9386782323",
    user_id: "e845de33-7d23-4ac6-a3c4-660ceca0cb8f",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 1,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "pixel art, dirt, mud, muddy wet floor texture, cave floor",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 50,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "cec2af65-bfb1-4916-be4c-b7bab6493ba7",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1748976250370,
    parent_grid: 0,
    parent_id: "839ce0c9-f735-4826-817c-224f61d3babc",
    width: 1024,
    height: 1024,
    username_v2: "smcante",
    display_name: "smcante",
    user_id: "319c4ed1-f898-486d-a800-fcde2dedf578",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 1,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Flat vector pattern of organic blobs in warm red and orange tones, abstract flow, seamless design on white background",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: [
        {
          content: "oyc2app",
          weight: 1,
        },
      ],
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "d75bbd20-5d31-4fe7-9daa-728c5bcbfdba",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1752204768652,
    parent_grid: 3,
    parent_id: "c0be52f7-15ca-4a4d-8a89-a0cd65e88340",
    width: 1024,
    height: 1024,
    username_v2: "gfkbpn03054v",
    display_name: "gfkbpn03054v",
    user_id: "974c4c42-04f5-4fc0-8163-1d269e15b6ff",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 1,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Generate an image with Filigree-like silver work,front view,intricate structure,irregular shapes,delicate and ornate patterns,sense of elegance, sophistication,intricate mechanical composition,soft lighting, high-end photography, HD, 8K, masterpiece, ultra-detailed, best quailty",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "6effa17a-fdab-41c2-bfa8-8c8e840170b4",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1752023996772,
    parent_grid: 3,
    parent_id: "29dfead0-ae10-4c12-a680-54621e466e6d",
    width: 1024,
    height: 1024,
    username_v2: "hoff8660",
    display_name: "hoff8660",
    user_id: "7f992895-8903-4ba5-91ff-2a10ebeb8bf5",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "perlin noise in black and white",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "4aac8591-9d53-4816-a0fc-49ea87930c02",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1752805810043,
    parent_grid: 1,
    parent_id: "d3fd9c57-85b5-49ac-8500-6693b7c3bf69",
    width: 1232,
    height: 928,
    username_v2: "gu8238",
    display_name: "gu8238",
    user_id: "849e616f-dd0c-43db-876a-14902aeff480",
    prompt: {
      no: ["color"],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 4,
        h: 3,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Fragmented parametric line textures arranged diagonally at 45 degrees, inspired by audio spectrum data, partial sine waves and broken curves, black and white 2D engraving texture, minimal and geometric, suitable for plastic surface engraving, seamless pattern，8k",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "bd32855d-8b64-4872-8eae-58a63adcd1aa",
    job_type: "v7_upscaler_2x_creative",
    event_type: "diffusion_upsample_v7_2x_creative",
    enqueue_time: 1752630737822,
    parent_grid: 3,
    parent_id: "5568811b-11b1-4007-9608-dad7abd98f23",
    width: 2048,
    height: 2048,
    username_v2: "nidhogg1390",
    display_name: "nidhogg1390",
    user_id: "f433a6f5-0801-4303-98d3-e0968cd2f478",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "norwegian shark skin texture alpha zbrush black and white",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 0,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "f49647ff-70a1-4c19-991f-202d060d915d",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1753340592115,
    parent_grid: 0,
    parent_id: "b465f8c3-0578-4590-841b-44a56bb63fd3",
    width: 1024,
    height: 1024,
    username_v2: "martelle_",
    display_name: "martelle_",
    user_id: "b2cff81d-19ce-4e12-923d-1120a556e11b",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "A plain pattern for a graphic to be applied on the floor for an innovation space inside sn edutainment building. The pattern should contain shapes which recalls innovation, techonoly and robots and should be recall Warby Parker style",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 50,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "f9527c22-ffff-435d-9300-a7de38107045",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1753749696782,
    parent_grid: 2,
    parent_id: "b5d16c28-12c9-40a6-8cec-2b35ed33c150",
    width: 1024,
    height: 1024,
    username_v2: "liakuluave",
    display_name: "liakuluave",
    user_id: "cbf8ae39-4dcf-444f-a7e1-4d7b793511ec",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "plain vintage background",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "66ba2bb9-d022-4c0d-aa31-e5e84ae75755",
    job_type: "v7_upscaler_2x_creative",
    event_type: "diffusion_upsample_v7_2x_creative",
    enqueue_time: 1754454774710,
    parent_grid: 0,
    parent_id: "e82c23bb-9176-4e26-8b4d-35bba3170da4",
    width: 2048,
    height: 2048,
    username_v2: "malifang_31499",
    display_name: "malifang_31499",
    user_id: "4975cc1e-cf15-451a-9e4e-745ab8b814da",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "Nuetral grey fuzzy, full screen pattern, transmission",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "303f058a-a748-4bc2-b59b-a57def0a1ec7",
    job_type: "v7_upscaler_2x_creative",
    event_type: "diffusion_upsample_v7_2x_creative",
    enqueue_time: 1754539373449,
    parent_grid: 1,
    parent_id: "aa5fb011-b88f-491f-bcb9-70613e6bacde",
    width: 2048,
    height: 2048,
    username_v2: "ncrrn",
    display_name: "ncrrn",
    user_id: "1f022c72-613c-450b-8b64-ae4526b38984",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "A black and grey thatched pattern",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "acbd07ff-1477-4b1d-8cec-3a6111142ffe",
    job_type: "v7_upscaler_2x_creative",
    event_type: "diffusion_upsample_v7_2x_creative",
    enqueue_time: 1755210351728,
    parent_grid: 0,
    parent_id: "11d0d3fd-ffc0-4714-85cc-46aba67e1599",
    width: 2048,
    height: 2048,
    username_v2: "cantbecontained",
    display_name: "Can't Be Contained!",
    user_id: "0f01b8d0-adc7-4e28-936c-b4c19faec571",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "black magic, psychadelic pattern swirls, in style of Shinji Kanda x YASHIRO Nanaco, black and white, vector, flat design, medium strokes, clean edges, dynamic movement, clearly legible, flat color, detailed vector",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "8394a67d-4732-4084-aaec-6e33b47c47c0",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1755251516817,
    parent_grid: 3,
    parent_id: "d8b87391-adb3-4b41-a530-656ff2682245",
    width: 928,
    height: 1232,
    username_v2: "ruanzhenyan",
    display_name: "ruanzhenyan",
    user_id: "c2fc6a8f-2ad0-4cb0-bc08-c81c37c0881c",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 3,
        h: 4,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Floral black and white Japanese pattern with sunflowers, seamless vector patterns, repeating designs, flat design, simple shapes, Japanese style, high resolution, white background, vector art, no shadows, no gradient, vector art, simple shapes, flat color blocks, black lines on a white background, no shading, no gradients.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: 2,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "d024b420-3340-4db0-a5a5-f04e0c030adb",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1756106748430,
    parent_grid: 1,
    parent_id: "cb15196f-7acd-4755-a898-2a937b004904",
    width: 896,
    height: 1344,
    username_v2: "leebonnie2248",
    display_name: "leebonnie2248",
    user_id: "9f406372-94bf-4b6a-b63d-970a9af555cf",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 85,
        h: 128,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "a seamless pattern of wavy, woven wool fabric with a unique ombre effect in brown, grey, and blue; the background is dark black. the design has an abstract, honeycomb-like structure that adds depth to each hexagonal shape, creating a textured surface that resembles natural fibers. each section wears its knitted texture as if it's made from real animal fur, in the style of a natural fiber.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "9e1c80d0-3f41-40a4-a3dd-a733eab0e258",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1756028025049,
    parent_grid: 3,
    parent_id: "6c266a2c-9242-4451-aac0-ca98b11c33c3",
    width: 1024,
    height: 1024,
    username_v2: "rickybenson",
    display_name: "rickybenson",
    user_id: "97965ab4-69dd-4dc3-bbce-1387049ed0e3",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 1,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "a stencil pattern of geometric shapes in black and white, arranged to form an intricate lace design. the background is pure white for easy coloring or engraving. a great idea! stencil patterns for adults.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "67c848fc-c4cb-4f11-9a49-beb6fb015a66",
    job_type: "v7_upscaler_2x_creative",
    event_type: "diffusion_upsample_v7_2x_creative",
    enqueue_time: 1756182744360,
    parent_grid: 3,
    parent_id: "4b453c6a-43c2-4ae8-9055-75b49ab40f16",
    width: 2464,
    height: 1856,
    username_v2: "zxspectrum",
    display_name: "Alex",
    user_id: "6210060f-0cfc-4de7-a5d8-d090eef53dce",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 4,
        h: 3,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "jasno szaro brązowy background for html www website, very exclusive , no items on it only pattern",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "ac1800a2-93cd-4c6a-bd16-80497a264ed6",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1756709007234,
    parent_grid: 0,
    parent_id: "cd1a3e90-6e05-41bb-9e63-dd9b6b35a21d",
    width: 1024,
    height: 1024,
    username_v2: "songbongdong",
    display_name: "songbongdong",
    user_id: "b766efb3-b778-452b-aa7d-93f18691f798",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "brand pattern, with logo",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "003a3ab8-2d28-4f02-a957-30087ad3351b",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1756311610217,
    parent_grid: 3,
    parent_id: "76118ae2-8e97-4a9c-896f-d8c188ed2907",
    width: 1024,
    height: 1024,
    username_v2: "sillysock429",
    display_name: "sillysock429",
    user_id: "1f63de55-f84a-4dfc-99e7-9df2fe3aa8c7",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "a printed detailed halftone texture overlay",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "33b55090-2aa2-4e5b-82ec-76f4372da312",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1756731709170,
    parent_grid: 2,
    parent_id: "78971e97-f5f3-425a-9d6c-937803df3a59",
    width: 1024,
    height: 1024,
    username_v2: "christian13131313",
    display_name: "christian13131313",
    user_id: "61c9946b-95f2-4bb8-aa6d-8cabf4e0e9d5",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "stencil sketch showing wavey 2d graphic, fabric, abstract",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 50,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "b39e572c-ee22-404e-82a2-7a8b842f226d",
    job_type: "v7_upscaler_2x_creative",
    event_type: "diffusion_upsample_v7_2x_creative",
    enqueue_time: 1756872234047,
    parent_grid: 3,
    parent_id: "ce482355-0ee8-4e2a-9916-bab885e471eb",
    width: 2048,
    height: 2048,
    username_v2: "tonydamico",
    display_name: "tonydamico",
    user_id: "cf6acfaf-18b2-454d-9d8d-7fca9b26d0b5",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "adbstract geometic patten that will be used as a background for marketing materials for a company called Rentvine. The images need to be in greyscale. Make it have some movement and 3D., make the overall patten feel wavy,. but keep the abstract shapes",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "a6af73ad-1300-4fe1-a387-4c555c136da1",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1757092292297,
    parent_grid: 3,
    parent_id: "4c08b3f5-c05e-4f42-bd7c-4d001f45e093",
    width: 1456,
    height: 816,
    username_v2: "strawburycreamcheese6335",
    display_name: "strawburycreamcheese",
    user_id: "2e693682-f89c-4812-b12b-aebec803fca7",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 16,
        h: 9,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "many tiny imperfect beige circles on a white background. the circles are very small, oddly shaped, and fill up the entire screen. the circles are all very similar in size and the same color.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "5220fde0-7695-4bce-9e6a-95c3be4af5eb",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1757435053116,
    parent_grid: 3,
    parent_id: "e0a3097a-a2cf-4c0b-b3ee-e59d750e2f41",
    width: 2048,
    height: 2048,
    username_v2: "u9461279321",
    display_name: "u9461279321",
    user_id: "c5a7b453-2440-41b0-ad5a-5d42b87ab3a3",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "some very simple, flat graphics style, linear, straight and long, black cracks in parallel lines on a completely white, flat surface, seen face on",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "c832d125-278c-4475-a516-aac2f18167e3",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1757788005970,
    parent_grid: 0,
    parent_id: "47242b27-5294-44c2-b7b4-d653091559a1",
    width: 1024,
    height: 1024,
    username_v2: "09c74fc0-c7c5-4013-8e74-df5133e2db08",
    display_name: "karrshow",
    user_id: "09c74fc0-c7c5-4013-8e74-df5133e2db08",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "white stitched texture super small high detail simple fractal noise",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "c7613c6e-c3e5-4401-adca-4d81d0c188ed",
    job_type: "v7_upscaler_2x_creative",
    event_type: "diffusion_upsample_v7_2x_creative",
    enqueue_time: 1758004939408,
    parent_grid: 3,
    parent_id: "ffe3237a-5032-416c-acfc-91a4a27c0ac0",
    width: 2048,
    height: 2048,
    username_v2: "u6469738721",
    display_name: "u6469738721",
    user_id: "a90636c1-4180-420f-8f9b-c58e9d4b7c67",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "beach sand overhead from distance with small ripple pattern for virtual environment",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "41fb4637-78fe-49c1-b355-e22130dc166a",
    job_type: "v7_upscaler_2x_creative",
    event_type: "diffusion_upsample_v7_2x_creative",
    enqueue_time: 1758178084030,
    parent_grid: 0,
    parent_id: "764d4e86-b22f-471d-9185-761714f1a7af",
    width: 2048,
    height: 2048,
    username_v2: "art_jie",
    display_name: "art_jie",
    user_id: "44e4df21-4532-424b-b579-187740eb5316",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "Monochromatic continuous abstract geometric pattern",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "6ec1f9e2-1a0b-4613-aef8-15ee00cc2753",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1758632191816,
    parent_grid: 0,
    parent_id: "2bdbc9da-3d11-4be1-9751-a2eecb546cc8",
    width: 2464,
    height: 1856,
    username_v2: "martin-thedesigner",
    display_name: "martin-thedesigner",
    user_id: "87169a7f-b011-431b-854a-76c9e75dd189",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 4,
        h: 3,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "matcha plants pattern illustration, outline, black white only, minimal, artistic",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: [
        {
          content: "2j3mm35",
          weight: 1,
        },
      ],
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 0,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "e6df2e93-7520-474e-ab6f-10a759a3d5cd",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1759538337977,
    parent_grid: 0,
    parent_id: "b1f54d92-841f-4df5-a211-c56e9cf255f3",
    width: 1632,
    height: 2912,
    username_v2: "lcyuen102",
    display_name: "lcyuen102",
    user_id: "67689108-b795-402a-b4a7-8ddae04a2ada",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 9,
        h: 16,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "vertical phone wallpaper, full frame twist Damascus steel texture, spiral wavy metallic patterns, polished black and silver steel, intricate details, abstract background, 9:16 aspect ratio",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: true,
      styleRef: [],
      personalize: [
        {
          content: "mvy1tw2",
          weight: 1,
        },
      ],
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "2039e83f-22e3-4704-bb63-163f612a4093",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1761307123585,
    parent_grid: 2,
    parent_id: "618dd211-fc7a-4adc-9b36-481a6cc28fde",
    width: 1856,
    height: 2464,
    username_v2: "artsyimp",
    display_name: "impa",
    user_id: "f224aa95-9c3d-4f8d-b4b9-5f3fc25e51c1",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 3,
        h: 4,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "A stencil of black golthic wallpaper",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "f5eaf78c-8a76-473d-ba67-8f995eafe4f8",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1762525169251,
    parent_grid: 1,
    parent_id: "f41cbc64-3cab-4ddf-9867-5584b34c5d39",
    width: 1024,
    height: 1024,
    username_v2: "ricardodieguez",
    display_name: "ricardodieguez",
    user_id: "52bcdf15-06b7-47bf-9837-3da7e1a9ac5c",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "minimalist black and white swirl pattern inspired by ocean currents, elegant flowing lines, abstract wave motion, high-contrast solid fills, suitable for a large wall mural, 10x30 ft installation in Fort Lauderdale, clean vector style, seamless composition, modern coastal aesthetic, no text, no gradients, high detail, black and white only",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "9fe57e85-1122-4c1a-9842-e024dea341ed",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1763084143284,
    parent_grid: 2,
    parent_id: "1f5979c0-b763-4436-99af-73e45cf3e0a8",
    width: 1024,
    height: 1024,
    username_v2: "12125f70-5739-47c1-b273-7787ff31624e",
    display_name: "keithsantiago1388",
    user_id: "12125f70-5739-47c1-b273-7787ff31624e",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Regular stripe elements with precisely aligned edges, seamless cyclic splicing, the pattern extends naturally without breakpoints, and the whole is coherent and unified.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "f1a97c4a-97fe-4336-b554-508e5d493f90",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1763296931215,
    parent_grid: 0,
    parent_id: "d807c8c4-8fee-4cc7-abf7-ff906bb51bb8",
    width: 2048,
    height: 2048,
    username_v2: "u52557619138too",
    display_name: "u5255761913too",
    user_id: "5f484396-7538-4502-b3a7-df49327715f9",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "create rare gold wallpaper texture wallpaper pc",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "93caaa94-0f06-4bd0-b7d4-25bdefc65268",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1764246196040,
    parent_grid: 0,
    parent_id: "d23db36d-5bdc-4175-9c3b-d9bd1717fccc",
    width: 1024,
    height: 1024,
    username_v2: "jynxi",
    display_name: "jynxi",
    user_id: "78f007c6-482c-4e51-bd5a-2643beaeb662",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "black filigree delicate swirls, white background",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "5a0b71eb-aaa0-4598-8511-4d85f463e067",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1765751145163,
    parent_grid: 0,
    parent_id: "40a5ae80-f96a-4b8d-9904-6ad8d36ae669",
    width: 1024,
    height: 1024,
    username_v2: "sixi",
    display_name: "sixi",
    user_id: "e4975b0a-d74b-4795-a607-d259232a0bd5",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 1,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "pattern, black and white",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: [
        {
          content: "yf3bcd1",
          weight: 1,
        },
      ],
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "c6f6279f-6971-44a0-b73e-033fcdf0db48",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1765581430098,
    parent_grid: 2,
    parent_id: "27dce047-68ed-4fcc-b955-bdcc81d1d3f4",
    width: 2688,
    height: 1792,
    username_v2: "geppoon",
    display_name: "geppoon",
    user_id: "66920521-c962-451d-b130-8385f73c95ff",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 3,
        h: 2,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "curly very simple vector art viking jewerly pattern, sinuous, black and white, based on real viking artifacts elegant",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: 2,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 250,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "30553f81-4b57-420f-9f4e-9df2a60bef1c",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1766890669616,
    parent_grid: 1,
    parent_id: "1dbb0f90-c15f-4cce-ab37-e582bca77340",
    width: 3072,
    height: 1536,
    username_v2: "gerry6315",
    display_name: "gerry6315",
    user_id: "ca8b5768-412c-4e17-b10f-e6f4bfc6d001",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 2,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "abstract line art pattern, vector, simple shapes, black and white, seamless, repeating, inspired in the style of keith haring. Reverse the white and black. More black with very fine white lines",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: [
        {
          content: "48g9vps",
          weight: 1,
        },
      ],
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "3ba04d50-f5aa-4ae0-9b77-8d51e6eb65b9",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1767658959763,
    parent_grid: 1,
    parent_id: "f72be4d0-2d57-4f7a-bd51-308c185b4a5d",
    width: 1856,
    height: 2464,
    username_v2: "has447",
    display_name: "has0584",
    user_id: "b096dcd3-8fde-43a8-843e-957be54ec835",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 3,
        h: 4,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Subtle repeating geometric diamond pattern, tone-on-tone deep teal background, extremely low contrast, soft matte texture, minimalist luxury style, barely visible pattern, clean modern design, seamless background, suitable for metal sublimation",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "fef3789c-7724-454f-bd67-370331c3e01c",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1768361613974,
    parent_grid: 3,
    parent_id: "3276b3c9-cfce-4369-92cc-5dc36e3ee229",
    width: 1232,
    height: 928,
    username_v2: "3e227b29-4387-4d94-a1f0-248b66b59749",
    display_name: "hsdfgjsdf_86287",
    user_id: "3e227b29-4387-4d94-a1f0-248b66b59749",
    prompt: {
      no: [
        "Texture,Relief",
        "moire, aliasing, jagged edges, pixelated seams, blocky artifacts, tiling, grid lines, stitching artifacts, compression artifacts, banding, checkerboard pattern, mosaic seams, over-sharpening, excessive microtexture",
      ],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 4,
        h: 3,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Seamless dark gray damask texture pattern on a black background creates an elegant and sophisticated design, suitable for various applications requiring strong color contrast and a luxurious and refined look. McKinney-style damask illustrations bring a unique visual experience, adding depth to any project.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 75,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "afab0e06-e9c5-4505-a8b7-677caf1d31ec",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1769711267687,
    parent_grid: 1,
    parent_id: "1dc67830-df9e-4534-81ca-142231a1e006",
    width: 2464,
    height: 1856,
    username_v2: "u4261672953",
    display_name: "u4261672953",
    user_id: "839c9dc0-da82-46db-a470-0aa1af7746f2",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 4,
        h: 3,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "dynamic abstract blob pattern, playful flowing shapes, high contrast black and white design, cute modern kids room wallpaper, inspired by organic cutout shapes, flat vector illustration, pure black and pure white only, no gradients, no gray, no depth, seamless tile pattern",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "8352bdd7-e7b0-48d9-988c-571e90134e43",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1770486173767,
    parent_grid: 3,
    parent_id: "db8dc37b-f0f4-4d67-83ef-5ac96ca52523",
    width: 1856,
    height: 2464,
    username_v2: "blaronn2k24",
    display_name: "blaronn",
    user_id: "37846233-f4dd-49ae-abb2-633e0a40b221",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 3,
        h: 4,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Growth Currents Pattern abstract lines work basic shapes bright blue contrast with dark deep blue coral reef",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 50,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "41bec86c-99b2-4bf7-a12d-b6c25e0c6c73",
    job_type: "v7_upscaler_2x_creative",
    event_type: "diffusion_upsample_v7_2x_creative",
    enqueue_time: 1771455822389,
    parent_grid: 0,
    parent_id: "43c6606c-4665-4f03-ae8e-5bbe7a18d64e",
    width: 2912,
    height: 1632,
    username_v2: "u7718842362",
    display_name: "u7718842362",
    user_id: "567ebca7-55d6-421b-83bc-0f44c49b56aa",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 16,
        h: 9,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "create a high end, classic luxury shape pattern in black and white solid outline",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "bbf42269-03b6-4542-9b84-0e58d807fe94",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1772506729310,
    parent_grid: 0,
    parent_id: "05717989-c718-4b63-b4ff-1bde9dfba649",
    width: 1920,
    height: 2400,
    username_v2: "u4317647923",
    display_name: "u4317647923",
    user_id: "95b46475-e1fa-4c83-b3a7-6ab5f73f3427",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: 5,
      ar: {
        w: 4,
        h: 5,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            'dark luxury backdrop, traditional east asian "auspicious cloud" swirl pattern as subtle embossed brocade, pattern concentrated in the top-left corner and faintly in bottom-right corner, large negative space in the center, smoky fog layers across the middle, charcoal black and deep gray palette, tiny bronze-gold dust speckles, cinematic low-key lighting, heavy vignette, ultra detailed texture, no objects, no people, no text',
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: 2,
      tile: false,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 80,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "8225bb1a-9e19-458e-9291-94a0711f3751",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1772563312182,
    parent_grid: 1,
    parent_id: "db7cbf25-1118-4f3e-a6b3-56726237c290",
    width: 3072,
    height: 1536,
    username_v2: "brycealexthomas",
    display_name: "brycealexthomas",
    user_id: "c6822ff6-ae20-4aa0-9aff-feb7532452b6",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 2,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Seamless repeating medieval inspired pattern on pure white background, detailed antique engraving style linework, cribbage pegs illustrated in classic 17th century woodcut style, small evenly spaced peg clusters arranged symmetrically, subtle elongated oval scoring track shapes woven into the layout, delicate ornamental scroll flourishes connecting elements, black ink line art on white background, flat illustration, no shading, no gradients, high detail etched lines, balanced spacing with clean negative space, old world craftsmanship aesthetic, elegant medieval decorative surface design, evenly tileable repeat pattern",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "45f8e96d-82d5-41aa-8062-d11552609008",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1772664293497,
    parent_grid: 3,
    parent_id: "afabe55a-ec3c-4a2b-b744-d59da43274db",
    width: 1024,
    height: 1024,
    username_v2: "atomicaxe",
    display_name: "atomicaxe",
    user_id: "6cd36669-ffb7-4b91-a219-a784ca51ff59",
    prompt: {
      no: ["grey, gradients"],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Elegant monochrome floral scroll pattern, large curved leaf motifs with spiral tendrils and dotted accents, seamless repeat layout, black ink on white background, decorative vintage wallpaper style, sharp vector illustration, 2d high contrast vector style,",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "8c6f81eb-1d0f-47a9-a994-f85da421293a",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1773300740794,
    parent_grid: 0,
    parent_id: "522b8e5d-2b3a-4cec-978e-0eaeb0d4ef9d",
    width: 1024,
    height: 1024,
    username_v2: "boboo",
    display_name: "zzw6317",
    user_id: "ffbb1b8c-940c-4af7-ab1e-4f598b6624c4",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 1,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "sculpted diamond pattern relief texture, repeating rhombus shapes, artistic geometric background, luxury label design, soft lighting, elegant minimal aesthetic, seamless pattern",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "084a07e8-8368-4241-9e4a-ab0b89a1c536",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1773942657864,
    parent_grid: 3,
    parent_id: "cd24a216-fd14-4756-bbe9-87b9cdc29d34",
    width: 928,
    height: 1232,
    username_v2: "txy20230509",
    display_name: "txy20230509",
    user_id: "f5d98a8c-7f4f-4053-9eac-db29a5e7d0a4",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 3,
        h: 4,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "a gray knitted fabric with wavy lines, textured background, and detailed pattern.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "5b768014-1013-4caa-b6c9-29662dc38b06",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1774424941353,
    parent_grid: 2,
    parent_id: "97274c78-3396-4b54-bc6a-37a29f9f75de",
    width: 1456,
    height: 816,
    username_v2: "muzzlehatch",
    display_name: "muzzlehatch",
    user_id: "28627563-54c0-44f4-92cd-f76aa03d1fc5",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 16,
        h: 9,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "ultra-minimal dot grid, microscopic perfect circles, ice white background, dots barely visible with extreme subtlety, soft gaussian blur toward all edges dissolving into nothing, one corner slightly denser creating asymmetric visual weight, breathable negative space, luxury editorial aesthetic, high-end corporate design",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 80,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "ac5ea0c8-73df-4e7e-9232-2364149c1cc6",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1774727405252,
    parent_grid: 0,
    parent_id: "24afb5ee-3845-479b-bcf2-14490151022b",
    width: 1456,
    height: 816,
    username_v2: "angie_5524",
    display_name: "angie_5524",
    user_id: "e2d79a92-1286-4f36-ac8f-b55359430f54",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 16,
        h: 9,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "monochrome relief",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "ce42613b-886e-4b76-a6b7-66351daba0ca",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1775456133816,
    parent_grid: 3,
    parent_id: "b6a4bca1-3ab1-48e7-969e-9cebbaa1d093",
    width: 1024,
    height: 1024,
    username_v2: "gnometoss",
    display_name: "gnometoss",
    user_id: "ae8aaf22-ac68-4e46-88fb-f1cdaab72dac",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "simple black vector stencil of sprinkles. on white paper. svg cut file design.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
];
