export default [
  {
    isFeedJob: true,
    id: "41466399-0774-4621-8967-97ea09413d4e",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1744619581514,
    parent_grid: 3,
    parent_id: "ce2861a9-d00b-40d3-8391-56a3c40028d1",
    width: 2048,
    height: 2048,
    username_v2: "shivashanty",
    display_name: "shivashanty",
    user_id: "8eaa4791-78d4-4454-a195-16a8b82c0b97",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "seamless pattern of vintage foliage",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "1eb9714a-d6fe-4fd9-8bd6-0dfe8e6b19cd",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1745277125143,
    parent_grid: 1,
    parent_id: "ca4a305a-19a4-4508-a7f4-51a930b8f3ad",
    width: 896,
    height: 1344,
    username_v2: "wintermute.dende",
    display_name: "wintermute.dende",
    user_id: "34386dc6-f2bf-4e07-b5f5-9e9e4fe8e8c4",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 2,
        h: 3,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "texture vector illustration, 3d graffiti style, swirling spiral smoke in the style of James Jean, well defined, complex dmt trip swirls, swirls and spirals, on white background",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "28c4cc80-cf5b-457d-b926-bd64f3161e8c",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1745048886142,
    parent_grid: 2,
    parent_id: "59916720-f5c3-47bc-91af-5ca0fbe8bae6",
    width: 816,
    height: 1456,
    username_v2: "artmmisthebest",
    display_name: "artmmisthebest",
    user_id: "8364ba26-3fdf-48fa-8c86-afc134ce6bba",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 9,
        h: 16,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Black geometric curves texture, arranged in a regular pattern, realistic light and shadow, realistic rendering, camera shot texture.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "43b43baf-61a6-44f7-ae6f-43a3affe4f3d",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1748338525024,
    parent_grid: 2,
    parent_id: "7ee7414f-4415-404f-a2ba-f9208c0e2158",
    width: 1024,
    height: 1024,
    username_v2: "u9386782323",
    display_name: "u9386782323",
    user_id: "e845de33-7d23-4ac6-a3c4-660ceca0cb8f",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 1,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "pixel art, dirt, mud, muddy wet floor texture, cave floor",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 50,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "5c06a8be-d42b-4e86-a7ba-bfb322fd248e",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1748495637396,
    parent_grid: 3,
    parent_id: "37b13a8d-4520-4035-b39a-0f7d16535583",
    width: 2048,
    height: 2048,
    username_v2: "novalab",
    display_name: "novalab",
    user_id: "970fee1a-19fd-4aa1-9227-88c46f6ca25c",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "pattern, organic forms, polygonal, black lines on white background, symmetrical",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "cec2af65-bfb1-4916-be4c-b7bab6493ba7",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1748976250370,
    parent_grid: 0,
    parent_id: "839ce0c9-f735-4826-817c-224f61d3babc",
    width: 1024,
    height: 1024,
    username_v2: "smcantex",
    display_name: "smcante",
    user_id: "319c4ed1-f898-486d-a800-fcde2dedf578",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 1,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Flat vector pattern of organic blobs in warm red and orange tones, abstract flow, seamless design on white background",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: [
        {
          content: "oyc2app",
          weight: 1,
        },
      ],
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "f7621e0c-9292-4379-949f-cfe516ab191d",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1748763179699,
    parent_grid: 0,
    parent_id: "91a2fda9-06c4-4862-9018-e6d4d5b36ce6",
    width: 1856,
    height: 2464,
    username_v2: "mishamishenkamishok",
    display_name: "mishamishenkamishok",
    user_id: "8ca6b382-9519-4a38-8550-acd515c67259",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 3,
        h: 4,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "grey fabric texture",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: [
        {
          content: "nhkoerc",
          weight: 1,
        },
      ],
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 50,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "ae41d779-b891-4d32-a83d-e6ce8e3d6ebd",
    job_type: "v7_upscaler_2x_creative",
    event_type: "diffusion_upsample_v7_2x_creative",
    enqueue_time: 1749761899733,
    parent_grid: 3,
    parent_id: "8af21b19-1f32-403d-9143-3630cc075b83",
    width: 2048,
    height: 2048,
    username_v2: "wrendel",
    display_name: "wrendel",
    user_id: "b33ab30e-74ae-4b61-889c-560d430b54d1",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "style core aesthetics",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "87191cb8-46d4-4b63-9bab-6466d9a85ced",
    job_type: "v7_upscaler_2x_creative",
    event_type: "diffusion_upsample_v7_2x_creative",
    enqueue_time: 1750316035945,
    parent_grid: 2,
    parent_id: "079b0433-4e66-4da6-b192-9356be428def",
    width: 2048,
    height: 2048,
    username_v2: "sublimation",
    display_name: "David",
    user_id: "883849b7-d7af-43e7-bd4a-dccfd2f13d92",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "3d art of a rubber surface with big bumps, bumps have a fine dot texture",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "e5d58503-f076-4fc2-b16e-1ec6f57f7707",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1750668475593,
    parent_grid: 0,
    parent_id: "cc817ba3-ea3c-4152-90e9-1aa20133418a",
    width: 2048,
    height: 2048,
    username_v2: "rainbowlion3057",
    display_name: "rainbowlion3057",
    user_id: "96e0eafb-bd3a-4d8d-976c-6bf67da21622",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "black and white cutout, wavey pattern, seemless texture",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "09e94e97-cc20-4d99-88b4-a13c534657d6",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1750949214091,
    parent_grid: 3,
    parent_id: "42617f80-7309-4198-ab0d-d6ad61e5070e",
    width: 2048,
    height: 2048,
    username_v2: "u9844485235",
    display_name: "u9844485235",
    user_id: "83bb74a4-8de0-44e9-b1d6-4f0458315da9",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 1,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Seamless vector pattern with vertical lines, each line 3mm thick, spaced exactly 2.5 cm apart. The lines subtly curve and intersect with neighboring lines to form a wavy, flowing structure across the pattern. The intersections create an elegant ripple or wave-like effect, adding visual rhythm and fluidity while maintaining strict vertical alignment. Style: minimal, geometric, seamless pattern, clean design. Color: single-tone (e.g. soft black on white or pastel accent on neutral). Output: seamless repeatable tile, vector-style precision, clean background.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 650,
      weird: 500,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "4653ad73-f25a-4ded-8138-447e8e67c231",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1750949601847,
    parent_grid: 0,
    parent_id: "62c25aab-a08a-42e1-82f0-ca423e99db40",
    width: 1024,
    height: 1024,
    username_v2: "u6165356918",
    display_name: "u6165356918",
    user_id: "f73ea3bf-973d-4344-af45-5d9abbe29b70",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "A vertical repeating pattern inspired by the segments of a scorpion's tail, representing arrogance. Each module is a hard, geometric, armor-like shape. When repeated, they form an infinite, defensive column. Brutalist and monumental graphic design, black and white, 2D.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 250,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "cb016e70-f556-453a-baac-aa9cb387d8c3",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1751012994834,
    parent_grid: 3,
    parent_id: "f485ef66-0fea-43c4-acee-8eddd7624eef",
    width: 2048,
    height: 2048,
    username_v2: "u4934796837",
    display_name: "u4934796837",
    user_id: "2c792470-9486-4cbd-92f7-9af6f0bc785a",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "crea uno sfondo in stile pattern che sfuma dal giallo in alto all'arancione in basso con piccole palline da tennis tono su tono che si vedono leggermente",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "68d9ea3d-2f90-489c-b31e-f60d352f0cda",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1751380348432,
    parent_grid: 2,
    parent_id: "a3f784a5-0b58-47b6-bac8-6ac7e0a2b3ed",
    width: 1024,
    height: 1024,
    username_v2: "mizukaji",
    display_name: "mizukaji",
    user_id: "4292463d-a526-4fca-bade-d77668b6bc12",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "greyscale raised sloped triangle seamless pattern",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "4f89853e-bf0d-496e-9cd3-5020ecc846f3",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1751428213517,
    parent_grid: 3,
    parent_id: "e5901ef3-7137-435c-92a0-1df8f7ae3e2a",
    width: 960,
    height: 1248,
    username_v2: "betsyhuizi",
    display_name: "betsyhuizi",
    user_id: "b93c4ceb-aa3b-43b7-bdea-16590c62c55d",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 99,
        h: 128,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            'A pattern of small, vertical lines of varying thickness and height scattered across the canvas in black ink. The background is dark grey, with each line representing different sizes or "strokes" in an abstract form. This creates a textured surface that adds depth to any design using it as a base for digital art or graphic creation.',
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 50,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "ff2473df-ed28-412a-8591-9dbb43df8e61",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1751854418253,
    parent_grid: 3,
    parent_id: "d79fd120-60e9-489e-9f8c-88abf67ff6cf",
    width: 1024,
    height: 1024,
    username_v2: "lxy06437",
    display_name: "lxy06437",
    user_id: "8e4c216b-19a3-4a7a-bdfd-f649166e7d5e",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Seamless pattern, a black and white vector illustration of a traditional Russian ornament in the style of Khokhloma, featuring elements of clouds, flowers, and swirls. This vector art has a cartoon, flat design with simple details and a minimalistic aesthetic. The image is of high resolution, high detail, high quality, high definition, high sharpness, high contrast, high clarity, high color saturation, high saturation, high vibrance, and high-texture rendering.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "5178deda-235b-42b8-aaa4-5fec32cdd2f4",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1754158357877,
    parent_grid: 3,
    parent_id: "687f4e1d-3649-4022-96e1-79a3c1b285cd",
    width: 1024,
    height: 1024,
    username_v2: "schnee2378",
    display_name: "schnee2378",
    user_id: "0f5db361-2a3e-452b-9de8-f8e482602fb6",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "abstract organic linocut print black and white",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "303f058a-a748-4bc2-b59b-a57def0a1ec7",
    job_type: "v7_upscaler_2x_creative",
    event_type: "diffusion_upsample_v7_2x_creative",
    enqueue_time: 1754539373449,
    parent_grid: 1,
    parent_id: "aa5fb011-b88f-491f-bcb9-70613e6bacde",
    width: 2048,
    height: 2048,
    username_v2: "ncrrn",
    display_name: "ncrrn",
    user_id: "1f022c72-613c-450b-8b64-ae4526b38984",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "A black and grey thatched pattern",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "8abda5df-468e-448f-be3c-d26c7d7ff657",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1755074207235,
    parent_grid: 2,
    parent_id: "d5933ad8-1db4-472d-aa10-689612577260",
    width: 1024,
    height: 1024,
    username_v2: "yukun001.",
    display_name: "yukun001.",
    user_id: "2087f44d-8c1b-428b-9c7c-26d39d54cf98",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "A seamless texture, with worn details that give it depth and character. This pattern would be perfect for creating realistic medieval or fantasy-themed game graphics, desert-inspired design with flowing dune-like patterns, encircled by ornate gothic-style bands, intricate carvings and reliefs, subtle weathering, warm sandy tones, high detail, cinematic lighting, hyper-realistic style",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "8394a67d-4732-4084-aaec-6e33b47c47c0",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1755251516817,
    parent_grid: 3,
    parent_id: "d8b87391-adb3-4b41-a530-656ff2682245",
    width: 928,
    height: 1232,
    username_v2: "ruanzhenyan",
    display_name: "ruanzhenyan",
    user_id: "c2fc6a8f-2ad0-4cb0-bc08-c81c37c0881c",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 3,
        h: 4,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Floral black and white Japanese pattern with sunflowers, seamless vector patterns, repeating designs, flat design, simple shapes, Japanese style, high resolution, white background, vector art, no shadows, no gradient, vector art, simple shapes, flat color blocks, black lines on a white background, no shading, no gradients.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: 2,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "c7a7d910-cd58-4c78-afc2-5b531505841f",
    job_type: "v7_upscaler_2x_creative",
    event_type: "diffusion_upsample_v7_2x_creative",
    enqueue_time: 1756106794793,
    parent_grid: 3,
    parent_id: "37ccb8b6-8e96-4f35-b932-c0e11738226c",
    width: 2048,
    height: 2048,
    username_v2: "hansuhyeok.",
    display_name: "hansuhyeok.",
    user_id: "088b9a70-85bf-49d4-aaa6-ed99f3f96a66",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: 35,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "decorative concrete wall with vertical 3D patterns, geometric embossed texture, modern architectural facade, light gray cement material, seamless pattern, uniform ambient lighting, ultra high resolution.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 0,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "cbaa41bb-3384-4346-bef6-10c6d5fc3484",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1758766854613,
    parent_grid: 2,
    parent_id: "0a2df31a-66e6-496e-95ef-7b77380b981a",
    width: 2048,
    height: 2048,
    username_v2: "grinningduck",
    display_name: "grinningduck",
    user_id: "60f20d41-8909-43f0-88ff-0de0cfae0a80",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "Black and silver repeating pattern, optical illusion",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "75c71429-5ec5-4b77-ba1f-04e17023be76",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1759868313779,
    parent_grid: 1,
    parent_id: "a07f2534-ea1b-4801-9ccf-056dd263e909",
    width: 2048,
    height: 2048,
    username_v2: "nicolaskoe",
    display_name: "nicolaskoe",
    user_id: "39b132a2-aefb-4df3-9c1f-6baff9fe73b9",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "make a 100% numerique vector pattern black and white of chiness geometric waves",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 0,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "58638f0b-4382-416f-834d-db483b784e6f",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1759950728797,
    parent_grid: 3,
    parent_id: "11cadfda-1a39-42db-8c50-37263877f71d",
    width: 1024,
    height: 1024,
    username_v2: "u1668996511",
    display_name: "u1668996511",
    user_id: "27e3e082-8ff7-4a79-94ff-62943040cc37",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "fish skin pattern in black and white. white background",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "2039e83f-22e3-4704-bb63-163f612a4093",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1761307123585,
    parent_grid: 2,
    parent_id: "618dd211-fc7a-4adc-9b36-481a6cc28fde",
    width: 1856,
    height: 2464,
    username_v2: "artsyimp",
    display_name: "impa",
    user_id: "f224aa95-9c3d-4f8d-b4b9-5f3fc25e51c1",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 3,
        h: 4,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "A stencil of black golthic wallpaper",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "3c27f85f-a9c4-4fe2-8b7d-0875535909c7",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1762436559807,
    parent_grid: 3,
    parent_id: "87cd1fdf-0a00-4e7e-8a17-c1e60bf5f41b",
    width: 2048,
    height: 2048,
    username_v2: "mangosalad",
    display_name: "mango",
    user_id: "1d8a3f5b-d895-4492-a882-e10715346260",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 1,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "seamless repeating background pattern inspired by baroque theater design. soft warm golden-beige and deep red tones, subtle ornamental textures, faint floral and scroll motifs, gentle gradient lighting as if illuminated by stage light. with hints of Slavic ornament and fairy-tale motifs subtly woven into the baroque texture. Elegant, minimal, without strong central elements, perfectly tileable, matte paper texture, suitable for luxury packaging or candy box design, no text, no borders, decorative but subtle, continuous repeating surface",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "9ef1ff75-20a7-4162-82b3-3c414573ec4c",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1763137894203,
    parent_grid: 2,
    parent_id: "fc3377c4-a956-46eb-b20d-12cb3be58816",
    width: 2048,
    height: 2048,
    username_v2: "3d3895a9-9afe-4e91-b444-a0526e1630e8",
    display_name: "u9811845418",
    user_id: "3d3895a9-9afe-4e91-b444-a0526e1630e8",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "dense field of ultra-short pencil strokes, clustered micro-hatching, scattered tiny marks in organic flowing groups, architectural site-plan vegetation texture, hand-drawn, monochrome, very soft contrast, seamless pattern, no long strokes, no blades of grass nno hard straight borders between the hatches",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 0,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "9c2b8fc2-d08d-4b5b-8cf5-4d1f941d8af6",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1763157478339,
    parent_grid: 0,
    parent_id: "49790314-e4a3-4ec0-b34d-fb64321ebbd6",
    width: 1024,
    height: 1024,
    username_v2: "johndeveloper09",
    display_name: "johndeveloper09",
    user_id: "ff0917b7-a04d-4a2e-9f61-27b34004a000",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "tea leafs pattern flat vector pattern. Black white style. Paul Rand design",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "131508d1-2ff4-4536-9cc0-586ad853b8f6",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1763434182279,
    parent_grid: 2,
    parent_id: "3912fdcc-da4e-4c8d-9c08-19b425484eae",
    width: 2048,
    height: 2048,
    username_v2: "itsmikawl",
    display_name: "itsmikawl",
    user_id: "7782ba92-c265-4c69-aadd-428b3f09773a",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "vectorized swirl theme background for wallpaper for an asian restaurant",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "e26ec488-911e-483a-98ca-eed4d2619825",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1764215638019,
    parent_grid: 3,
    parent_id: "f4203898-1e0b-44c8-80b6-a8d44091e691",
    width: 1024,
    height: 1024,
    username_v2: "wangyi09",
    display_name: "wangyi09",
    user_id: "e9a174a7-19bd-4e21-9a06-84e00cff076c",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 1,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "abstract geometric pattern with irregular interconnected shapes, maze-like dark outlines on light background, tileable texture.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 250,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "ad80a9c4-7fea-4f4b-a3ab-7ac6cca6a677",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1765053335360,
    parent_grid: 2,
    parent_id: "9f1dfacd-ba74-4c71-9717-271ea9e0e546",
    width: 1024,
    height: 1024,
    username_v2: "racheliti",
    display_name: "racheliti ceu",
    user_id: "54ccc101-9bfd-495c-abfd-82a63ed65b6e",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 1,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "seamless flowing topographic vector lines, thick smooth contour curves, black lines on white background, no color, no glow, no shading, no texture, minimal vector style, perfectly repeating tile",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 10,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "c1eaa0e0-fbe2-4189-a78a-eacb4726adca",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1765308129459,
    parent_grid: 3,
    parent_id: "0c3d0dbd-7862-4770-88f4-819be9ed179d",
    width: 2464,
    height: 1856,
    username_v2: "hovmand",
    display_name: "Hovmand",
    user_id: "c28e2407-9b03-49e7-90bc-6aa142222024",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 4,
        h: 3,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "wallpaper old style with round pattern. stylish. and black licorice",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "7af87cdb-db05-4424-a667-cae22b339830",
    job_type: "v7_upscaler_2x_creative",
    event_type: "diffusion_upsample_v7_2x_creative",
    enqueue_time: 1765773492900,
    parent_grid: 0,
    parent_id: "41535f57-9e06-461f-b42c-15b139051552",
    width: 2048,
    height: 2048,
    username_v2: "yaremka",
    display_name: "_yaremka_",
    user_id: "af2a0af6-891d-485e-b5e1-fff8ef9e91ca",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "liquid chrome droplets flowing and merging into a seamless repeating pattern, futuristic glossy digital-art, macro composition, smooth tileable layout, soft cold studio reflections",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [
        {
          t: "seed",
          content: "3354566889",
          weight: 1,
        },
      ],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "f893896e-e3eb-412d-aa35-16c4bd0af73a",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1766141074543,
    parent_grid: 1,
    parent_id: "cb3bdaf0-5a44-4792-a7a1-45848fae2e28",
    width: 960,
    height: 1248,
    username_v2: "b28986c5-3d19-42e9-970e-ed77e3eef67d",
    display_name: "kingdow1217",
    user_id: "b28986c5-3d19-42e9-970e-ed77e3eef67d",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 99,
        h: 128,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "a seamless pattern of an intricate geometric tech grid, in light blue and grey on a white background, with subtle fine details, in a digital print style.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: 2,
      tile: true,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "31cb2c09-4e97-4d6c-85d1-fcbeda3b0499",
    job_type: "v7_upscaler_2x_creative",
    event_type: "diffusion_upsample_v7_2x_creative",
    enqueue_time: 1766845896633,
    parent_grid: 1,
    parent_id: "1f6d1793-e8ed-4c0f-b931-d6171bedbe81",
    width: 2048,
    height: 2048,
    username_v2: "plyr78",
    display_name: "PLYR78",
    user_id: "9872a78a-8e80-4c21-8556-ecae4bdfca35",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Black and white endless drawing pattern in an contemporary style",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "ddb345b6-9b8c-45a1-9e7d-71604648ee3a",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1767186858842,
    parent_grid: 0,
    parent_id: "6801165b-3b99-4f9f-a1b0-055fc1534392",
    width: 2592,
    height: 1824,
    username_v2: "rodrigoestevamm",
    display_name: "rodrigoestevamm",
    user_id: "8436fe92-6f84-464c-bbab-65af6f4248b7",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 10,
        h: 7,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "a multi-directional tossed pattern of large-scale abstract foliage, bold graphic style, 2D flat illustration, high contrast, vibrant royal blue on a clean white background",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: true,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 0,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "9c5068e5-41d9-41fd-970a-4a01c587db2e",
    job_type: "v7_upscaler_2x_creative",
    event_type: "diffusion_upsample_v7_2x_creative",
    enqueue_time: 1767796577726,
    parent_grid: 3,
    parent_id: "eb0daaed-abf5-478d-afdb-d1904ea9ecce",
    width: 4352,
    height: 1088,
    username_v2: "lcampb30",
    display_name: "Lcampb30",
    user_id: "9817ccc2-cd7d-46d6-b129-8d67975e7a28",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: 15,
      ar: {
        w: 4,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "flat vector illustration, continuous horizontal box pattern, organic brain-cell inspired blob shapes, dopamine neural flow style, smooth rounded liquid forms, interconnected blobs flowing left to right, strictly confined inside a clean horizontal rectangular band, flat white shapes on solid black background, no gradients, no shadows, no texture, no depth, no noise, crisp vector edges, minimal modern graphic design, packaging border pattern, seamless rhyth",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "fef3789c-7724-454f-bd67-370331c3e01c",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1768361613974,
    parent_grid: 3,
    parent_id: "3276b3c9-cfce-4369-92cc-5dc36e3ee229",
    width: 1232,
    height: 928,
    username_v2: "3e227b29-4387-4d94-a1f0-248b66b59749",
    display_name: "hsdfgjsdf_86287",
    user_id: "3e227b29-4387-4d94-a1f0-248b66b59749",
    prompt: {
      no: [
        "Texture,Relief",
        "moire, aliasing, jagged edges, pixelated seams, blocky artifacts, tiling, grid lines, stitching artifacts, compression artifacts, banding, checkerboard pattern, mosaic seams, over-sharpening, excessive microtexture",
      ],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 4,
        h: 3,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Seamless dark gray damask texture pattern on a black background creates an elegant and sophisticated design, suitable for various applications requiring strong color contrast and a luxurious and refined look. McKinney-style damask illustrations bring a unique visual experience, adding depth to any project.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 75,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "31becae3-ae12-4749-9be9-c7b208600d53",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1768807505048,
    parent_grid: 3,
    parent_id: "41c7ff6a-04cb-4131-bf28-ae2a6cd8f241",
    width: 2048,
    height: 2048,
    username_v2: "u6593755937",
    display_name: "u6593755937",
    user_id: "fbeb3b2e-e32f-4f6a-9199-ce8ccc6694a6",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "black and white geometric radioactive grain texture. vector graphics.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "8e780ea8-724f-4326-9f5e-aa4c8a3e1e5b",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1769643349045,
    parent_grid: 2,
    parent_id: "714f5311-0c8e-4509-881e-756b5789aac2",
    width: 2912,
    height: 1632,
    username_v2: "oldsoulartist",
    display_name: "oldsoulartist",
    user_id: "cc0a8b0d-9325-4926-90d3-c1fe59e7a22c",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 16,
        h: 9,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "White corpoart background pattern, minimal",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "63ee9762-54ee-4615-93e5-5051e24819c2",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1770864664114,
    parent_grid: 1,
    parent_id: "4d086ef2-1ffa-4f3e-b57e-8efcd026f8b4",
    width: 2048,
    height: 2048,
    username_v2: "cw1817",
    display_name: "cw1817",
    user_id: "16717280-a009-4517-a118-e7cd80917b50",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "seamless repeating vector pattern, rattan basket weave, over under interlaced strips, uniform spacing, crisp edges, flat 2D illustration, no gradients, no lighting, clean textile pattern, consistent scale",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "ce3bc8ef-aa91-464f-b27a-0d3f0751e4a1",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1771348749183,
    parent_grid: 1,
    parent_id: "dc7aeed2-c86b-4c08-9eda-78abe8fb2598",
    width: 2048,
    height: 2048,
    username_v2: "bucks1111",
    display_name: "bucks1111",
    user_id: "b7b0c11d-0860-4557-a429-36c2c3bec751",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "texture, 2D, caustics light reflections, greyscale",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "49f7f0f9-ddb2-4e6f-b0e2-7f085050527f",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1771359284095,
    parent_grid: 2,
    parent_id: "090df2ec-0a3a-4c08-be0a-b1c9e3e149d6",
    width: 1024,
    height: 1024,
    username_v2: "sintheticsanity",
    display_name: "sintheticsanity",
    user_id: "229dd8f2-4bac-4225-b9d9-f6cf3a2620ba",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "black and white gothic swirls with thorns design",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "bbf9310a-23b4-4785-b812-2453a839f477",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1771952646301,
    parent_grid: 3,
    parent_id: "aa258102-b077-4b12-b075-0e79efade536",
    width: 1232,
    height: 928,
    username_v2: "442812cd-c4c1-4b1d-b77f-e68fab1c26c5",
    display_name: "sportsmen0112",
    user_id: "442812cd-c4c1-4b1d-b77f-e68fab1c26c5",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 4,
        h: 3,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content: "an orange and white pattern with organic shapes, seamless.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "8225bb1a-9e19-458e-9291-94a0711f3751",
    job_type: "v7_upscaler_2x_subtle",
    event_type: "diffusion_upsample_v7_2x_subtle",
    enqueue_time: 1772563312182,
    parent_grid: 1,
    parent_id: "db7cbf25-1118-4f3e-a6b3-56726237c290",
    width: 3072,
    height: 1536,
    username_v2: "brycealexthomas",
    display_name: "brycealexthomas",
    user_id: "c6822ff6-ae20-4aa0-9aff-feb7532452b6",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 2,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Seamless repeating medieval inspired pattern on pure white background, detailed antique engraving style linework, cribbage pegs illustrated in classic 17th century woodcut style, small evenly spaced peg clusters arranged symmetrically, subtle elongated oval scoring track shapes woven into the layout, delicate ornamental scroll flourishes connecting elements, black ink line art on white background, flat illustration, no shading, no gradients, high detail etched lines, balanced spacing with clean negative space, old world craftsmanship aesthetic, elegant medieval decorative surface design, evenly tileable repeat pattern",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "af9a0ec1-d428-4550-9fa5-244320060554",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1774527468215,
    parent_grid: 2,
    parent_id: "f8232be5-299e-42dd-9204-31b2859e1b11",
    width: 1904,
    height: 640,
    username_v2: "59222503-fd64-4702-84c1-6f70b959ae22",
    display_name: "hanne715",
    user_id: "59222503-fd64-4702-84c1-6f70b959ae22",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 3,
        h: 1,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "create a pattern of metal turning parts using only lines and geometric shapes like circles, stripes, etc.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: 50,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "f31757ba-05ed-40fb-8762-1e37a82c69e2",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1774598209318,
    parent_grid: 3,
    parent_id: "42e72c64-9208-42c1-9ddc-95392f0c7ea1",
    width: 928,
    height: 1232,
    username_v2: "joeldee57c1516",
    display_name: "joeldee57c1516",
    user_id: "492d18b1-12a1-4179-a7c4-70eaeb1f8443",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: {
        w: 3,
        h: 4,
      },
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Minimalist seamless Damask pattern, solid gray-orange and chocolate brown, abstract floral silhouettes, flat design, no textures, no gradients, simple geometric shapes, high contrast, tileable",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: true,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "c7c8677b-003a-4837-addf-692e494ed0bd",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1774844658327,
    parent_grid: 3,
    parent_id: "dd388393-4d78-4bd2-843b-0098b36d5bcd",
    width: 1024,
    height: 1024,
    username_v2: "gabi99025",
    display_name: "gabi99025",
    user_id: "00b753d3-d227-4d74-a6cf-26d4b0b78821",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "Generate a geometric pattern based on a single irregular tile (non-square shape), repeated across a plane. The tile should have a continuous curved or linear motif that connects seamlessly when rotated. The pattern must demonstrate how rotation of one identical tile creates variation and complexity. Use a minimal black-and-white palette, precise linework, and a clean architectural diagram style. Emphasize modular repetition, rotation, and continuity across edges.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
  {
    isFeedJob: true,
    id: "5cd8721a-61f4-47e3-932c-201d4c215275",
    job_type: "v7_virtual_upsample",
    event_type: "diffusion_upsample_v7_virtual",
    enqueue_time: 1774727818704,
    parent_grid: 3,
    parent_id: "fd70977a-8d78-4138-b0ae-dc505f4f5e05",
    width: 1024,
    height: 1024,
    username_v2: "reigne27",
    display_name: "reigne27",
    user_id: "1281ebb2-1a72-4666-9c88-1a14dbbdf4e8",
    prompt: {
      no: [],
      images: [],
      stop: null,
      chaos: null,
      ar: null,
      seed: null,
      speed: null,
      visibility: null,
      batchSize: null,
      exp: null,
      decodedPrompt: [
        {
          content:
            "minimal organic abstract pattern, in the style of vector style, pattern inspired by shapes from nature, bio-ecosystem in abstract way, vector hand-made, isolated in white background, black and white, seamless, psychedelic.",
          weight: 1,
        },
      ],
      params: null,
      version: "7",
      quality: null,
      tile: false,
      styleRaw: false,
      styleRef: [],
      personalize: false,
      pv: null,
      sv: null,
      sw: null,
      omniRef: [],
      ow: null,
      depthRef: [],
      dw: null,
      stylize: null,
      weird: null,
      imageWeight: null,
      zoom: null,
      video: false,
      draft: false,
    },
    published: true,
    items: [
      {
        filtered: false,
        liked_by_user: false,
        actions: {},
        server_filtered: false,
      },
    ],
    owner_profile: null,
    type: "image",
    video_segments: null,
  },
];
